[package]
name = "dbus-cec"
version = "0.1.0"
edition = "2024"
description = "DBus service for Raspberry Pi that for TV power control through HDMI-CEC"
license = "MIT"
authors = ["Bogdan Mircea"]

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = {}
depends = ["libcec6", "libp8-platform2"]
assets = [
    { source = "target/release/dbus-cec", dest = "/usr/bin/dbus-cec", mode = "0755" },
    { source = "assets/com.home.HdmiCec.conf", dest = "/usr/share/dbus-1/system.d/com.home.HdmiCec.conf", mode = "0644" }
]

[package.metadata.cross.target.aarch64-unknown-linux-gnu]
dockerfile = "Dockerfile"

[dependencies]
cec-rs = { version = "12", default-features = false }
serde = { version = "1", default-features = false, features = ["std", "derive"] }
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
