name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check format
        run: cargo +nightly fmt --check

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Check docs
        run: cargo doc --workspace --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings

  clippy:
    name: Clippy
    needs: [format, docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --workspace
        env:
          RUSTFLAGS: -D warnings

  release:
    name: Release DEB packages
    needs: clippy
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcec-dev libp8-platform-dev libudev-dev

      - name: Build rpi-dbus-cec DEB package
        run: cargo deb -p rpi-dbus-cec

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/debian/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
